project:
  type: website
  output-dir: docs

website:
  title: "proback.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - courses.qmd
      - 02_maps.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
